### ISSUE TITLE
onclickoutside could be usefull

### ISSUE THREAD

**Issue by stephanedemotte** [svelte-u/docs#1]
Hello juste an idea, onclickoutside is a usefull function :)

https://svelte.dev/repl/0ace7a508bd843b798ae599940a91783?version=3.16.7 or https://vueuse.org/core/onClickOutside/

Thanks !

**Comment by Mohamed-Kaizen** [comment]
Hi @stephanedemotte,

The `onClickOutside` function is a good idea, but I've temporarily paused development on the project due to Svelte 5 changes. I want to see how Svelte 5 evolves before refactoring and adding support for `runs`. I'm also unsure about the `runs` concept, so I'm leaning towards continuing with Svelte 4 until the  default approach is no longer supported.

Thanks for the suggestion! I'll definitely consider adding it in the future.

Thanks :)
